name: learning-github-actions

on: [create, delete, workflow_dispatch]

jobs:
  callme:
    runs-on: ubuntu-latest
    steps:
      - name: Printing secret
        run: echo ${{ vars.TESTING_VARIABLE }}
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
