name: learning-github-actions

on: 
  create:

jobs:
  callme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Hello Bash
        run: echo 'Hello, bash!'
