name: Learning github actions

on: [create]

jobs:
  callme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn 
