name: learning-github-actions

on: [create, delete]

jobs:
  callme:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn
